### ISSUE TITLE
Check script is recognized as connected client

### ISSUE THREAD

**Issue by wernerfred** [seosepa/check-teamspeak3-perf#1]
Hi,
i use your script in my icinga2 instance and it works really well but i figured out an annoying thing.
It seems like the check script is recognized as a connected client for the time of the connection and therefore the check script will always return one more "player" online than it is.

Currently there are no clients online at my server but the response from your plugin is:
```
OK: ts.****.de has 1/32 clients online and is running for 97 days
```
Due to this missleading information there is logically also a following error at ```clientpercentage```

Can you reproduce this faulty behavior? Maybe it will be fixed by simply substract 1 from ```$currentClients```

**Comment by conFrituur** [comment]
Hi Wernerfred,

Thank for reporting this issue, i have been able to reproduce this on my own server as well. It seems connected queryclients are included in the total client count. i will try to push a fix later this week.

**Comment by wernerfred** [comment]
I would like to add your plugin as a submodule to my monitoring-plugins collection - if you don't mind?
Check it out here: https://github.com/wernerfred/monitoring-plugins/ 
If you disagree i will remove it :)
If yes, can you therefore add a release if you push the fix mentioned above?

**Comment by conFrituur** [comment]
Done and done, have fun :)
